# Generated by Django 4.1.7 on 2023-02-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.FloatField()),
                ('sqft_living', models.IntegerField()),
                ('sqft_lot', models.IntegerField()),
                ('floors', models.FloatField()),
                ('waterfront', models.CharField(choices=[(0, 'NON'), (1, 'OUI')], max_length=1)),
                ('view', models.CharField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], max_length=1)),
                ('condition', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=1)),
                ('grade', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13)], max_length=2)),
                ('sqft_basement', models.IntegerField()),
                ('yr_built', models.IntegerField()),
                ('yr_renovated', models.IntegerField()),
                ('zipcode', models.IntegerField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
